name: Build and Deploy Jekyll + mdBook

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Restore cached 2025 mdBook
        id: cache-mdbook-2025
        uses: actions/cache@v4
        with:
          path: 2025/slides/haskell
          key: mdbook-2025-0.4.52-${{ hashFiles('2025/slides/_haskell/**') }}

      - name: Setup mdBook 0.4.52 for 2025
        if: steps.cache-mdbook-2025.outputs.cache-hit != 'true'
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: '0.4.52'

      - name: Build mdBook for 2025
        if: steps.cache-mdbook-2025.outputs.cache-hit != 'true'
        run: mdbook build 2025/slides/_haskell -d ../haskell

      - name: Restore cached 2026 mdBook
        id: cache-mdbook-2026
        uses: actions/cache@v4
        with:
          path: 2026/slides/haskell
          key: mdbook-2026-0.5.4-katex-0.10.0-${{ hashFiles('2026/slides/_haskell/**') }}

      - name: Setup mdBook 0.5.4 for 2026
        if: steps.cache-mdbook-2026.outputs.cache-hit != 'true'
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: '0.5.4'

      - name: Install mdBook KaTeX 0.10.0 for 2026
        if: steps.cache-mdbook-2026.outputs.cache-hit != 'true'
        run: cargo install mdbook-katex --version 0.10.0 --locked

      - name: Build mdBook for 2026
        if: steps.cache-mdbook-2026.outputs.cache-hit != 'true'
        run: mdbook build 2026/slides/_haskell -d 2026/slides/haskell

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build
        uses: actions/jekyll-build-pages@v1

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
